import React from 'react'

const Section1 = () => {
  return (
    <div id='disclaimer-section1'>
      <h2>Disclaimer</h2>
      <p>Protection from the Financial Services Compensation Scheme (“FSCS”) only considers claims against failed regulated firms. Learn more about FSCS protection using the following link: <a href="https://www.fscs.org.uk/what-we-cover/investments/" target="_blank" rel="noopener">www.fscs.org.uk/what-we-cover/investments</a></p>
      <p>The Financial Ombudsman Service (“FOS”) will not be able to consider complaints related to this firm. If you have a complaint against an FCA regulated firm, FOS may be able to consider it. Learn more about FOS protection using the following link: <a href="https://www.financial-ombudsman.org.uk/consumers" target="_blank" rel="noopener">www.financial-ombudsman.org.uk/consumers</a></p>
      <p>If you are interested in learning more about your protections then you can visit he FCA’s website on <a href="https://www.fca.org.uk/investsmart" target="_blank" rel="noopener">www.fca.org.uk/investsmart</a></p>
      <p>The content of promotional marketing material will have been approved by an authorised person in line with the definition provided by the Financial Services and Markets Act 2000.</p>
      <p>The tax treatment of this business depends on the individual circumstances of each investor and may be subject to change. It may be prudent to consider seeking professional and/or financial advice before investing.</p>
      <p>Past performance and forecasts are not indicating future performance. The value of investment may rise or fall depending on external factors that Wealthfusion Limited are unable to control.</p>
      <p>The access to the relevant products / services / investment opportunities may not be suitable or appropriate for all recipients and it should be noted that your capital could be at risk. As an investor, you should consider carefully whether such investment opportunities are suitable in the light of personal circumstances and the financial resources available to you.</p>
      <p>This document has been produced solely for information purposes, by Wealthfusion Limited with the greatest of care and to the best of its knowledge and belief for use by its legal entities, products and services.</p>
      <p>The information contained herein constitutes a marketing communication and should not be construed as financial research or analysis, an offer, a public offer, an investment advice, a recommendation or solicitation to buy, sell or subscribe to financial instruments and/or to the provision of a financial service.&nbsp; Further, this document is not intended to provide any financial, legal, accounting or tax advice and should not be relied upon in this regard.</p>
      <p>The information provided herein is for the exclusive use of the recipient and may not be reproduced, disclosed or distributed, neither in part nor in full. &nbsp;this document is not directed at, or intended for distribution to or use by, any person or entity domiciled or resident in any jurisdiction where such distribution, publication, availability or use would be contrary to applicable laws or regulations of such jurisdictions.</p>
      <p>Any investment decision must be based on a prior study of the offering documentation and in particular the terms and conditions and key information documents. This information can be obtained on request and will be free of charge from your relationship manager.</p>
      <p>The content of this document is intended only for persons who understand and are capable of assuming all risks involved. This document has been prepared without taking into account the investor classification, specific investment objectives, financial situation, tax situation or the needs of the recipient.&nbsp; Products and services are not suitable for all investors and may not be available to investors residing in certain jurisdictions or with certain nationalities.&nbsp; Before entering into any transaction, the recipient should consider the suitability of the transaction to individual circumstances and objectives. Wealthfusion Limited recommends that investors independently assess, with a professional financial advisor, the specific financial risks as well as the legal, regulatory, credit, tax and accounting consequences.&nbsp; Investment products may be subject to investment risks involving, but not limited to, possible loss of all or part of the principal investment. This document is not intended to be exhaustive on all risks related to financial instruments. Therefore, the recipient should consult the specific product documentation and discuss any queries with their relationship manager prior to entering into an investment decision.</p>
      <p>The information and views expressed at the time of writing are subject to change at any time without notice and there is no obligation to update or remove outdated information.&nbsp; Historical data on the performance of the securities and financial instruments or the underlying assets in this document is no indication for future performance and the value of investments may fall as well as rise. This document is based on publicly available information and data.&nbsp; Although information in this document has been obtained from sources believed to be reliable, Wealthfusion Limited provides no guarantee with regard to the timeliness, accuracy or completeness of the information and does not accept any liability for any loss and / or damage, either directly or indirectly, arising out of or in connection with the use of all or part of this information or from the omission of certain information.</p>
      <p>Recipients should be aware that the terms and conditions and key information documents constitute the sole binding basis for the purchase of investment funds.&nbsp; Some investments may foresee restrictions to target group of investors.</p>
    </div>
  )
}

export default Section1