export const MenuData =  [
    {
        name:"Services",
        path:"/services"
    },
    {
        name:"About",
        path:"/about"
    },
    {
        name:"Insights",
        path:"/insights"
    },
    {
        name:"Impact",
        path:"/impact"
    },
    {
        name:"Contact",
        path:"/contact"
    },
]