import React from 'react'

const Section1 = () => {
  return (
    <div id='terms-section1'>
      <h2>TERMS & CONDITIONS</h2>
        <h4>Disclaimer</h4>
        <p>These Terms of Use apply to the Wealthfusion Limited (“Wealthfusion”) website as well as any other affiliated sites, digital services, or applications on which a link to these Terms of Use appears (collectively, the “Wealthfusion Website”) and apply to all visitors. These Terms of Use and any other terms that appear on the page from which you were directed to these Terms of Use govern your use of the Wealthfusion Website. By accessing the Wealthfusion Website, you agree to be legally bound by the Terms of Use then in effect. Please also refer to the relevant additional legal information applicable to your country.</p>
        <p>These Terms of Use as well as the information and materials contained in the Wealthfusion website are subject to change by adding or removing features at any time and potentially without notice and at our sole discretion. Access to the Wealthfusion website following any modification in these Terms of Use will constitute your acceptance of the Terms of Use as modified.</p>
        <p>If you do not agree to be bound by these Terms of Use, do not use the Wealthfusion website for any further access or communication.</p>
        <h4>Access Subject to Local Restrictions</h4>
        <p>The Wealthfusion Website and all information and functionalities contained within them are not directed at or intended for use by any person resident or located in any jurisdiction where (1) the distribution of such information or functionality is contrary to the laws of such jurisdiction; or (2) such distribution is prohibited without obtaining the necessary licenses or authorizations by the relevant branch, subsidiary or affiliate office of Wealthfusion and such licenses or authorizations have not been obtained.</p>
        <h4>Services and Products</h4>
        <p>Products and services displayed on the Wealthfusion website may not be eligible for sale or available to residents of certain countries or certain categories of investors. Please consult the applicable terms and conditions such as sales restrictions or key specific notes for further information.</p>
        <p>Any materials, information or reports published, distributed or otherwise made available on the Wealthfusion Website is published for information purposes and is subject to change at any time without notice. Wealthfusion have no regard to the specific investment objectives, financial situation or particular needs of any specific recipient and should not be construed as a solicitation, offer or recommendation, to buy or sell any securities, investment or other financial instruments, to effect any transactions or to conclude any legal act of any kind whatsoever. Unless specifically stated otherwise, all price information is indicative only. No representation or warranty, either express or implied, is provided in relation to the accuracy, completeness or reliability of the materials, nor are they a complete statement of the securities, markets or developments referred to herein. The materials should not be regarded by recipients as a substitute for the exercise of their own judgment. Any opinions are subject to change without notice and may differ or be contrary to opinions expressed by other business areas or groups of Wealthfusion as a result of using different assumptions and criteria. Wealthfusion is not under any obligation to update or keep current the information contained herein nor to remove any outdated information from the Wealthfusion Website or to expressly mark it as being outdated.</p>
        <h4>No Offer</h4>
        <p>All information and materials published, distributed or otherwise made available on the Wealthfusion Website are provided for informational purposes, for your non-commercial, personal use only. No information or materials published on the Wealthfusion Website constitutes a solicitation, an offer, or a recommendation to buy or sell any investment instruments, to effect any transactions, or to conclude any legal act of any kind whatsoever.</p>
        <p>Wealthfusion does not provide investment, legal or tax advice through the Wealthfusion Website and nothing herein should be construed as being financial, legal, tax or other advice. Wealthfusion does not represent that any securities or services discussed are suitable for any investor. No investment or other decisions should be made solely based on the contents or information found on the Wealthfusion Website.</p>
        <p>When making a decision about your investments, you should seek the advice of a professional financial advisor or qualified expert.</p>
        <h4>Performance</h4>
        <p>The future performance of an investment cannot be deduced from previous market value, i.e. the value of an investment may fall as well as rise. An investment may also lose value due to changes in rates of foreign exchange. Wealthfusion cannot guarantee that any capital invested will maintain or increase in value.</p>
        <h4>Forward Looking Statements</h4>
        <p>The Wealthfusion Website may contain statements that constitute “forward looking statements”. While these forward looking statements may represent Wealthfusion judgment and future expectations, a number of risks, uncertainties and other important factors could cause actual developments and results to differ materially from Wealthfusion expectations. Wealthfusion is under no obligation to (and expressly disclaims any such obligation to) update or alter its forward looking statements whether as a result of new information, future events, or otherwise.</p>
        <h4>No Warranty</h4>
        <p>Your use of the Wealthfusion Website is at your own risk. The Wealthfusion Website, together with all content, information and materials contained therein, is provided “as is” and “as available” “, without any representations or warranties of any kind. Any materials, information or content accessed, downloaded or otherwise obtained through the use of the Wealthfusion Website is done at your own risk and Wealthfusion is not responsible for any damage to your computer systems or loss of data that results from the download of such material. Wealthfusion and its affiliates expressly disclaimer all representations or warranties of any kind, whether express or implied, with respect to the Wealthfusion Website, and all materials, information, content and functionalities contained herein, including but not limited to warranties of title, non-infringement, merchantability or fitness for a particular purpose. Without limiting the foregoing, Wealthfusion does not warrant the accuracy, timeliness, completeness, security, reliability or availability of the Wealthfusion Website or the information or results obtained from use of the Wealthfusion Website, or that the Wealthfusion Website will be available at all times, or is virus-free or error-free.</p>
        <h4>No Liability</h4>
        <p>To the fullest extent permitted by law, in no event shall Wealthfusion or our affiliates, or any of our directors, employees, contractors, service providers or agents have any liability whatsoever to any person for any direct or indirect loss, liability, cost, claim, expense or damage of any kind, whether in contract or in tort, including negligence, or otherwise, arising out of or related to the use of all or part of the Wealthfusion Website, or any links to third party websites.</p>
        <p>You are solely responsible for acquiring and maintaining such electronic devices and equipment that can handle and will allow you to access and use the Wealthfusion Website and for taking adequate and appropriate data security measures in accordance with good industry practice to protect yourself against fraud or cyber-attacks on a continuous basis (e.g. by using the most recent browser versions, and installing recommended security patches and up-to-date anti-virus programs and firewalls). Wealthfusion specifically disclaims all liability for any tampering with any user’s computer system by unauthorized parties, or for losses or liabilities suffered by any user arising from viruses or attacks by hackers.</p>
        <p>In no event will Wealthfusion or our affiliates, or any of our officers, directors, employees, contractors, service providers or agents be liable for any incidental, special, punitive or consequential damages howsoever caused arising out of the use of the Wealthfusion Website, its content, or the inability to use the Wealthfusion Website.</p>
        <p>This disclaimer of liability applies to any and all damages or injury, including those caused by any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communication line failure, theft, destruction, or unauthorized access, whether for breach of contract, tortious behavior, negligence or under any other cause of action.</p>
        <h4>Links</h4>
        <p>The Wealthfusion Website may contain third party content or links to third party websites. The content and links are provided solely for your convenience and information. Wealthfusion has no control over, does not assume any responsibility for and does not make any warranties or representations as to, any third party content or websites, including but not limited to, the accuracy, subject matter, quality or timeliness. Wealthfusion shall have no liability for third party content or websites or websites linking to or framing the Wealthfusion Website.</p>
        <h4>Social Bookmarks</h4>
        <p>The Wealthfusion Website may contain social bookmarks which are identifiable by means of their respective buttons. Social bookmarks allow users of certain social media platforms to post links to selected Wealthfusion web pages on their social media accounts in order to bookmark them or share them with their social media contacts. If you use social bookmarks, you will be sending personal identifying data to the respective social media platform. Any comments or activity made by or carried out by persons using social bookmarks is not controlled, endorsed or monitored by Wealthfusion and Wealthfusion shall not be responsible or liable for such. Persons who share Wealthfusion communications via social bookmarks are not authorized to speak for or represent Wealthfusion and their views and opinions must be regarded as strictly their own and not Wealthfusion. In addition, the provisions in these Terms of Use relating to Links also apply to social bookmarks.</p>
        <h4>Intellectual Property Rights</h4>
        <p>Wealthfusion, or the applicable third party owner, retains all right, title and interest (including copyrights, trademarks, patents, as well as any other intellectual property or other right) in all information and content (including all text, data, graphics and logos) on the Wealthfusion Website. Individual pages and/or sections of the Wealthfusion Website may be printed for personal or internal use only, and provided that such print outs retain all applicable copyright or other proprietary notices. All users must not, without limitation, modify, copy, transmit, distribute, display, perform, reproduce, publish, license, frame, create derivative works from, transfer or otherwise use in any other way, whether in whole or in part, any information, text, graphics, images, video clips, directories, databases, listings or software obtained from the Wealthfusion Website for commercial or public purposes, without the prior written permission of Wealthfusion. Systematic retrieval of content from the Wealthfusion Website to create or compile, directly or indirectly, a collection, compilation, database or directory (whether through robots, spiders, automatic devices or manual processes) or creating links to the Wealthfusion Website without the prior written permission from Wealthfusion is strictly prohibited.</p>
        <p>The key symbol and Wealthfusion are among the registered and unregistered trademarks of Wealthfusion. Other marks may be trademarks of their respective owners. Except as noted above, you may not use any trademarks of Wealthfusion for any purpose without the prior written permission of Wealthfusion.</p>
        <h4>Electronic Communication (E-Mail)</h4>
        <p>The Internet is an universally accessible medium. Ordinary e-mail messages sent over the Internet are neither confidential nor secure. They may be easily accessible by third parties and may entail a considerable amount of danger and risk including: (a) lack of confidentiality (e-mails and their attachments can be read and/or monitored without detection); (b) manipulation or falsification of the sender’s address or of the e-mail’s (or attachment’s) content (e.g. changing the sender’s address(es) or details); (c) system outages and other transmission errors, which can cause e-mails and. their attachments to be delayed, mutilated, misrouted and deleted; (d) viruses, worms, Trojan horses etc. may be spread undetected by third parties and may cause considerable damage; and (e) interception by third parties.</p>
        <p>You are therefore recommended to communicate with Wealthfusion by using a secure channel if such channel is provided by Wealthfusion. In no event should you use ordinary E-mail to transmit personal or confidential information such as any account related data.</p>
        <p>Unless explicitly stated otherwise, Wealthfusion does not accept any orders or instructions sent by E-mail or any other electronic messaging system.</p>
        <p>Wealthfusion shall not be liable to you or anybody else for any damages incurred in connection with any messages sent to Wealthfusion using ordinary E-mail or any other electronic messaging system.</p>
        <h4>Privacy Statement</h4>
        <p>Wealthfusion has established a Privacy Statement, as modified from time to time, which explains how personal data is collected on the Wealthfusion Website and used. The Privacy Statement is part of these Terms of Use and is incorporated herein by reference.</p>
        <h4>Severability Clause</h4>
        <p>To the extent that any provision of these Terms of Use is found by any competent court or authority to be invalid, unlawful or unenforceable in any jurisdiction, that provision shall be deemed to be severed from these Terms of Use but such finding shall not affect the validity, lawfulness or enforceability of the remainder of these Terms of Use in that jurisdiction, nor shall it affect the validity, lawfulness or enforceability of these Terms of Use in any other jurisdiction.</p>
        <h4>Conflict with Additional Terms</h4>
        <p>Certain web pages or areas on the Wealthfusion Website may contain additional terms, conditions, disclosures and disclaimers (collectively, the “Additional Terms”). In the event of a conflict between these Terms of Use and the Additional Terms, the Additional Terms will govern for those web pages or areas.</p>
        <p>Last updated in December 2024.</p>

    </div>
  )
}

export default Section1